/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import javax.swing.JOptionPane;

import event.EventMessage;
import event.PublicEvent;
import model.Model_Message;
import model.Model_Register;

/**
 *
 * @author Admin
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        CustomButtonRegistry();
    }
    private void CustomButtonRegistry(){
        cmdRegistry.setBackground(new java.awt.Color(104, 88, 219));
        cmdRegistry.setForeground(new java.awt.Color(255, 255, 255));
        cmdRegistry.setText("Đăng ký");
        cmdRegistry.setColorClick(new java.awt.Color(152, 196, 239));
        cmdRegistry.setColorOver(new java.awt.Color(219, 74, 131));
        cmdRegistry.setFillBorder(30);
        cmdRegistry.setFocusable(false);
        
        jLabel1.setVisible(false);
    
    }
    private void init(){
       
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new swing.PictureBox();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        cmdBackLogin = new javax.swing.JButton();
        cmdRegistry = new swing.Button();
        txtUserName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtRepass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/icon/register.png"))); // NOI18N

        cmdBackLogin.setContentAreaFilled(false);
        cmdBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackLoginActionPerformed(evt);
            }
        });

        cmdRegistry.setFont(new java.awt.Font("iCiel Mijas", 0, 15)); // NOI18N
        cmdRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistryActionPerformed(evt);
            }
        });

        txtUserName.setBorder(null);

        txtPass.setBorder(null);

        txtRepass.setBorder(null);

        jLayeredPane1.setLayer(cmdBackLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmdRegistry, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtRepass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(cmdBackLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48))
                    .addComponent(txtPass)
                    .addComponent(txtRepass)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(cmdRegistry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(txtRepass, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdRegistry, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdBackLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addContainerGap())
        );

        pictureBox1.add(jLayeredPane1);
        jLayeredPane1.setBounds(620, 200, 300, 250);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        pictureBox1.add(jLabel1);
        jLabel1.setBounds(620, 450, 310, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackLoginActionPerformed
         PublicEvent.getInstance().getEventLogin().goLogin();
    }//GEN-LAST:event_cmdBackLoginActionPerformed

    private void cmdRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistryActionPerformed
        String userName = txtUserName.getText().trim();
        String password = String.valueOf(txtPass.getPassword());
        String confirmPassword = String.valueOf(txtRepass.getPassword());
        if(userName.equals("")){
        	 JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người dùng!", "Thông tin thiếu sót", JOptionPane.WARNING_MESSAGE);
             txtUserName.grabFocus();
        }else if(password.equals("")){
        	 JOptionPane.showMessageDialog(this, "Vui lòng nhập password!", "Thông tin thiếu sót", JOptionPane.WARNING_MESSAGE);
            txtPass.grabFocus();
        }else if(!password.equals(confirmPassword)){
        	 JOptionPane.showMessageDialog(this, "Vui lòng nhập lại password!", "Thông tin thiếu sót", JOptionPane.WARNING_MESSAGE);
            txtPass.grabFocus();
        }else{
            Model_Register data = new Model_Register(userName, password);
            PublicEvent.getInstance().getEventLogin().Register(data, new EventMessage() {
                @Override
                public void callMessage(Model_Message message) {
                    if(!message.isAction()){ //if biến message ko phải true = false
                    jLabel1.setVisible(true);
                    jLabel1.setText(message.getMessage());
                    }else{
                        jLabel1.setText("Đăng ký tài khoản thành công !");
                        JOptionPane.showMessageDialog(null, "Đăng ký tài khoản thành công", "Thông báo",JOptionPane.INFORMATION_MESSAGE); 
                    }
                   }
            });
        }
    }//GEN-LAST:event_cmdRegistryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBackLogin;
    private swing.Button cmdRegistry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private swing.PictureBox pictureBox1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtRepass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
