/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import java.io.File;
import javax.swing.Icon;
import model.Model_Receive_Image;
import model.Model_Receive_Message;
import model.Model_Voice_Receive;

/**
 *
 * @author Admin
 */
public class Chat_Left extends javax.swing.JLayeredPane {

    /**
     * Creates new form Chat_Left
     */
    public Chat_Left() {
        initComponents();
        txt.setBackground(new Color(242, 242, 242));
    }
    public void setText(String text){
       if(text.equals("")){
        txt.hideText();
        }else{
         txt.setText(text);
        }
    }
    public void setImage(Icon... image) {
       //txt.setImage(false, image);
    }   
    public void setImage(Model_Receive_Image dataImage, File file) {
        txt.setImage(false, dataImage, file);
    }
    public void setFile(String fileName, String fileSize){
//        txt.setFile(fileName, fileSize);
        
    }
    public void setFile(Model_Receive_Message data){
        txt.setFile(false, data);
        
    }
    public void setEmoji(Icon icon){
        txt.hideText();
        txt.setEmoji(false, icon);
    }
    public void setSound(Model_Voice_Receive data){
       txt.setSound(false, data);
    }

    public void setTime() {
        txt.setTime("10:30 PM");    //  Testing
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new component.chat_Item();

        setLayer(txt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.chat_Item txt;
    // End of variables declaration//GEN-END:variables
}
