/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import event.PublicEvent;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import main.Main;
import model.Model_File_Sender;
import model.Model_Package_Sender;
import model.Model_Receive_Message;
import service.Service;
import swing.Progress;

/**
 *
 * @author Admin
 */
public class Chat_File extends javax.swing.JPanel {

    /**
     * Creates new form Chat_File
     */
    public Chat_File() {
        initComponents();
        setOpaque(false);
    }
    public void setFile(Model_Receive_Message data){
        String fileName = data.getDataImage().getFileName().split("!")[0];
        String fileSize = data.getDataImage().getFileName().split("!")[1];
        lbFileName.setText(fileName);
        lbFileSize.setText(fileSize);
         addEvent(this, fileName, data.getDataImage().getFileID());
        progress1.setProgressType(Progress.ProgressType.DOWN_FILE);
    
    }
    public void setFile(Model_File_Sender data){
        String fileName = data.getFileName().split("!")[0];
        String fileSize = data.getFileName().split("!")[1];
        lbFileName.setText(fileName);
        lbFileSize.setText(fileSize);
        addEvent(this, fileName, data.getFileID());
        progress1.setProgressType(Progress.ProgressType.DOWN_FILE);
    
    }
    
    private void addEvent(Component com, String fileName, int fileID){ //sự kiện khi nhấn chuột trái vào view image
        com.setCursor(new Cursor(Cursor.HAND_CURSOR));
        com.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(SwingUtilities.isLeftMouseButton(e)){
                  downloadFile(fileName, fileID);
                
                }
            }
        
        });
    }
   private void downloadFile(String fileName, int fileID){ //gửi request dến server, để down file về lưu vào folder
       try {
            String ex[] = fileName.split("\\.");
            String x = ex[ex.length - 1];
            JFileChooser ch = new JFileChooser();
            ch.setSelectedFile(new File(fileName));
            int c = ch.showSaveDialog(Main.getFrames()[0]);
            if(c == JFileChooser.APPROVE_OPTION){
              File f = ch.getSelectedFile();
              if(f.exists()){
              int click = JOptionPane.showConfirmDialog(Main.getFrames()[0], "Tệp này đã tồn tại trong thư mục, bạn có muốn thay thế nó không ?", "Lưu File", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                  if (click != JOptionPane.YES_OPTION) {
                        return;
                    }
              }
              String parth = f.getAbsolutePath();
               if (!parth.endsWith("." + x)) {
                    parth += "." + x;
                }        
            Model_Package_Sender data = new Model_Package_Sender();
            data.setFileID(fileID);
            data.setFileName(parth);
            data.setData(null);
            data.setFinish(true);
            System.out.println(data.getFileID()+" "+data.getFileName());
           
            Service.getInstance().getClient().emit("download", data.toJsonObject());
           }
            
           
           
           
         } catch (HeadlessException e) {
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress1 = new swing.Progress();
        jPanel1 = new javax.swing.JPanel();
        lbFileName = new javax.swing.JLabel();
        lbFileSize = new javax.swing.JLabel();

        progress1.setBorder(null);
        progress1.setProgressType(swing.Progress.ProgressType.FILE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        lbFileName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbFileName.setText("ádasdasdas");
        jPanel1.add(lbFileName);

        lbFileSize.setForeground(new java.awt.Color(70, 0, 151));
        lbFileSize.setText("2 MB");
        jPanel1.add(lbFileSize);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(progress1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progress1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void InitIconFile(){
     //icon file
      Image word = new ImageIcon(getClass().getResource("/icon/word.png")).getImage();
      Image txt = new ImageIcon(getClass().getResource("/icon/txt.png")).getImage();
      Image rar = new ImageIcon(getClass().getResource("/icon/rar.png")).getImage();
      Image pp = new ImageIcon(getClass().getResource("/icon/pp.png")).getImage();
      Image pdf = new ImageIcon(getClass().getResource("/icon/pdf.png")).getImage();
      Image exe = new ImageIcon(getClass().getResource("/icon/exe.png")).getImage();
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFileName;
    private javax.swing.JLabel lbFileSize;
    private swing.Progress progress1;
    // End of variables declaration//GEN-END:variables
}
