/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import java.time.LocalTime;
import javax.swing.Icon;
import model.Model_File_Sender;
import model.Model_Send_Message;
import model.Model_Voice_Receive;

/**
 *
 * @author Admin
 */
public class Chat_Right extends javax.swing.JLayeredPane {

    /**
     * Creates new form Chat_Left
     */
    public Chat_Right() {
        initComponents();
        txt.setBackground(new Color(211, 181, 255));//set màu khung chat
    }
    public void setText(String text){
       if(text.equals("")){
        txt.hideText();
        }else{
         txt.setText(text);
        }
       txt.seen();
       
    }
    public void setImage(Model_File_Sender fileSender) {
        txt.setImage(true, fileSender);
    }
    public void setImage(String... image) {
        //txt.setImage(false, image);   
    }
    public void setFile(Model_File_Sender data){
       txt.setFile(true, data);
        
    }
    public void setSound(Model_Voice_Receive data){
       txt.setSound(true, data);
    }
    public void setEmoji(Icon icon){
        txt.hideText();
        txt.setEmoji(true, icon);
    }

    public void setTime() {
        //        txt.setTime("10:30 PM"); 
        LocalTime time = LocalTime.now();
        String timeCurrent = time.toString();
        txt.setTime(timeCurrent.split(":")[0]+":"+timeCurrent.split(":")[1]);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new component.chat_Item();

        setLayer(txt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.chat_Item txt;
    // End of variables declaration//GEN-END:variables
}
